name: ParkourMaster
version: '1.0-SNAPSHOT'
main: com.vfcastro.dev.parkour.ParkourMaster
api-version: '1.21'
commands:
  parkour:
    description: "Make, edit or deleter a parkour track"
    usage: "/parkour <create | checkpoint | finish | reset> <name>"
